@controller=Authentication
# Register new user
POST {{base_url}}/{{controller}}/Register HTTP/1.1
Content-Type: application/json

{
	"username": "developer",
	"password": "Abc@1234",
	"email": "example@gmail.com",
  "phonenumber": "0123456789"
}

###

# Get bearer token
POST {{base_url}}/{{controller}}/Login HTTP/1.1
Content-Type: application/json

{
	"username": "developer",
	"password": "Abc@1234"
}

###

# Get refresh token
POST {{base_url}}/{{controller}}/RefreshToken HTTP/1.1
Content-Type: application/json

{
  "token": "{{bearer_token}}",
  "refreshToken": "{{refresh_token}}"
}