@controller=Teacher

# Get all teachers
GET {{base_url}}/{{controller}} HTTP/1.1

###

# Get teacher by id
@id=417982d3-8338-4d75-bc7c-08db0159e689
GET {{base_url}}/{{controller}}/{{id}} HTTP/1.1

###

# Get teacher by name
@name=Nhân
GET {{base_url}}/{{controller}}/{{name}} HTTP/1.1

###

# Add new teacher
POST {{base_url}}/{{controller}}
Content-Type: application/json
Authorization: Bearer {{bearer_token}}

{
  "fullName": "Nguyễn Đình Ánh",
  "email": "nd.anh@hutech.edu.vn",
  "phone": "0123456789",
  "customerId": null
}

###

# Update teacher
@id=417982d3-8338-4d75-bc7c-08db0159e689
PUT {{base_url}}/{{controller}}/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{bearer_token}}

{
  "fullName": "Nguyễn Đình Ánh",
  "email": "ndanh@hutech.edu.vn",
  "phone": "0123456789",
  "customerId": null
}

###

# Delete teacher
@id=dedd80ff-f505-4036-a3e3-30b477b5b017
DELETE {{base_url}}/{{controller}}/{{id}} HTTP/1.1
Authorization: Bearer {{bearer_token}}