@controller=Token
# Register new user
POST {{base_url}}/{{controller}}/register
Content-Type: application/json

{
	"username": "developer",
	"password": "Abc@1234",
	"email": "example@gmail.com",
  "phonenumber": "0123456789"
}

###

# Get bearer token
POST {{base_url}}/{{controller}}/getToken
Content-Type: application/json

{
	"username": "developer",
	"password": "Abc@1234"
}