version: '3.4'
services:
  rabbitmq:
    image: rabbitmq:3.8.9-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: Abc@1234